version: "3.2"
services:
  api:
    build: .
    ports:
      - "8765:8765"
    volumes:
      - $HOME/.aws:/root/.aws:ro
    environment:
      - MW_LOCAL_RUN=true
      - MW_AWS_REGION=${MW_AWS_REGION}
      - MW_TEMP_BUCKET_NAME=${MW_TEMP_BUCKET_NAME}