// Code generated by mockery v1.0.0. DO NOT EDIT.

package apimocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// UploadMedia provides a mock function with given fields: ctx, r, fileName
func (_m *Manager) UploadMedia(ctx context.Context, r io.Reader, fileName string) (string, error) {
	ret := _m.Called(ctx, r, fileName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string) string); ok {
		r0 = rf(ctx, r, fileName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string) error); ok {
		r1 = rf(ctx, r, fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
